package team2485.smartdashboard.extension;

import edu.wpi.first.smartdashboard.gui.Widget;
import edu.wpi.first.smartdashboard.properties.Property;
import edu.wpi.first.smartdashboard.types.DataType;
import javax.swing.border.TitledBorder;

public class LargeText extends Widget {
    public static final String NAME = "Large Text";
    public static final DataType[] TYPES = { DataType.NUMBER, DataType.STRING };

    @Override
    public void init() {
        initComponents();
        ((TitledBorder)this.getBorder()).setTitle(getFieldName());
    }
    
    @Override
    public void setValue(Object o) {
        if (o instanceof Number)
            valueField.setText((Number)o + "");
        else if (o instanceof String)
            valueField.setText((String)o);
    }

    @Override
    public void propertyChanged(Property prprt) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Label", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.BorderLayout());

        valueField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valueField.setText("000");
        valueField.setToolTipText("");
        add(valueField, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField valueField;
    // End of variables declaration//GEN-END:variables
}
